'''
Created on 21 Nov 2012

@author: epstvxj
'''

'''
 SGEH
'''
SGEH_EVENT_RECORD = 1
SGEH_ERROR_RECORD = 2
SGEH_FOOTER_RECORD = 3

SGEH_EVENT_ATTACH = 0
SGEH_EVENT_ACTIVATE = 1
SGEH_EVENT_RAU = 2
SGEH_EVENT_ISRAU = 3
SGEH_EVENT_DEACTIVATE = 4
SGEH_EVENT_DETACH = 14
SGEH_EVENT_SERVICE_REQUEST = 15

'''
 GPEH 
'''
GPEH_HEADER_RECORD = 0 # 420 bytes
GPEH_RECORDING_RECORD = 1
GPEH_PROTOCOL_RECORD = 2
GPEH_BODY_RECORD = 4
GPEH_LINK_RECORD = 8
GPEH_FOOTER_RECORD = 7
GPEH_ERROR_RECORD = 6


CAPTOOL_SUMMARY_FILENAME_SEARCH_STRING = '_summary_'
CAPTOOL_SUMMARY_FILENAME_EXT = '.log'
STAPLE_TCPTA_PARTIAL_FILENAME_SEARCH_STRING = '_staple_tcpta-partial_'
STAPLE_TCPTA_PARTIAL_FILENAME_EXT = '.log'